ajscroller1 = new AJScroller();
ajscroller1.name = 'ajscroller1';
ajscroller1.type = 0;
ajscroller1.width = 300;
ajscroller1.height = 200;
ajscroller1.spacing = 5;
ajscroller1.scrollspeed = 10;
ajscroller1.pausedelay = 100;
ajscroller1.pausemouseover = true;
ajscroller1.add('<em>My Story...<br>I have been overweight for years... <br>I tried nearly every diet that I could, and never lost more than 5 pounds.  I knew that my eating habits needed to change, but I lacked the will power to do it myself. <br>I also suffered from depression, which was making life miserable, for me and for my family. <br>I was angry at everything, when I used to be used to be such a cheerful person.  My life was in a rut, and I couldn\'t get out.  <br><br>...the hypnosis began to change my outlook on everything, the weight started coming off, and I have lost 20 pounds so far, and I am still working on another 20*.<br>As for my depression, I have totally gotten off of all medication, and am as cheerful as I used to be, I haven\'t had an anxiety attack in months...<br><br>On the whole, I have been so blessed to have this opportunity, it has changed my life.<br><br>I am happier.<br><br>My family is happier.<br><br>And I know that I could not have done it without The American Hypnosis Clinic."<br><br>- Robin Custalow<br>*She\'s lost over 60 lbs total since this writing!<a href="http://www.americanhypnosisclinic.com/testimonials.htm">(read her whole testimonial here)</a><br><br></em>', 't see much of a change in my weight, though my eating habits were altered immensely.  Then everything started to click together, since I had so many things to work on, the counseling that Dr. Burgess gave along with the hypnosis began to change my outlook on everything, the weight started coming off, and I have lost 20 pounds so far, though I am still working on another 20. I feel confident that it too<br>will come off in time.  Progress is slow, but I have yet to put any weight back on.  As for my depression, I have totally gotten off of all medication, and am as cheerful as I used to be, I haven', 'Custalow WL');
ajscroller1.add('<b>"I had to stop and figure it out… it\'s been over a year now without one cigarette and I have the American Hypnosis Clinic to thank.  What I love about them is that they stand behind you no matter what."<br><br>- Chuck Doud<br>Ex-smoker(In one session)</b><br><br>', '', 'dowd smoking');
ajscroller1.add('"Although I admit that I was somewhat apprehensive  when I called to make my appointment, <br>I have found the progress that I have made to be nothing short of amazing. <br><br>I have lost 20 lbs. in 57 days and even more importantly, I now "eat to live" instead of "living to eat". <br><br>This alone represents a significant change in the quality of my life and I am convinced that it is a sustainable change that I will live with for the rest of my life.<br><br>...I was a miserable failure with all of them [diets], but now I have been introduced to a method that I am convinced will change all of this forever.  <br><br>I simply can\'t express in words to you how much the American Hypnosis Clinic\'s program has meant to me already and I have just begun my journey towards good health and a fabulous life. <br>My family would only echo the things that I have shared with you and they might also add that I have become much easier to live with...<br><br>If I were ask to advise others that have areas in their lives that they find impossible to control, I would simply say... I find this to be the easiest and most effective method to address my issues that I have ever tried."<br><br>- Jim Hale<br>Lost it… and kept it off! <br><a href="http://www.americanhypnosisclinic.com/testimonials.htm">(read his whole testimonial here)</a><br><br>', '', 'Hale WL');
ajscroller1.add('<em>"It is simply amazing!  <br><br>I find I can do all the things I used to, but have NO cravings or desires to smoke.  <br>Sometimes I find myself reaching to my shirt pocket, only to find no cigarettes and realizing "oh, yeah… I don\'t smoke anymore!"  <br>I just take a deep breath, and the thought of smoking goes away.  <br><br>I still take my hourly breaks at work, but now it\'s for the fresh air, not the smoking.  <br><br>My sense of taste and smell are much better and all of this is happened within 48 hours of my session!! <br><br>My wife was so impressed, she did it too!  Great Program!"<br><br>- John Bastor, Ex-smoker<br>(In one session)<br><br></em>', '', 'Bastor Smoking');
ajscroller1.add('<b>"The program helps me forget about the pain and makes me feel normal again.  <br><br>Builds self confidence and helps me relieve stress.  <br><br>This program is great for people in pain to give them a chance in having a normal life.  Thanks!<br><br>- A.B.L..<br>Successfully managing chronic pain<br><br></b>', '', 'ABL Pain');
ajscroller1.add('"In two weeks I have lost 10 1/2 pounds.  I know it is due to hypnosis. <br><br> I have been able to stop snacking, to stop eating deserts, and to eat only things that are healthy.  <br><br>To me, this is unbelievable.  <br><br>I have tried various other methods to lose weight, but none of them dealt with the main problem -- which was always my thinking/beliefs!  <br><br>Individualized hypnosis was the answer , and am grateful beyond words to have the chance to finally have this help.  <br><br>Dr. Larry is a wonderful hypnotherapist, which made it even more pleasant than I expected/hoped.  You can be sure I will tell everyone who asks how I\'ve lost weight that I\'ve done (and continued to do) it through hypnosis.<br>Thank you Dr. Larry!"<br><br>- Nancy Levy<br>**** Since then she\'s lost another 43 lbs!<br><br>', '', 'Levy WL');
ajscroller1.add('<em>"I am very satisfied with the quit smoking method.<br><br>  It worked wonders for me.  <br><br>I never thought that I would be able to stop smoking for anyone.  <br>The staff & therapists are all great and very understanding to YOUR NEEDS."<br><br>Thanks again,<br>Melissa T. Morris<br>Ex-smoker<br><br></em>', '', 'Morris Smoker');
ajscroller1.add('<b>"After just one time of seeing Larry I feel more in control of what I am eating.  And how much I am eating.  <br>Things that I could not wait to eat just don\'t seem to call out to me like they did.  <br><br>I have lost 10.5 lbs* and am very happy with that.  And I feel that I can reach a goal that I have set for myself.  And know that once I get there I will be happier and healthier."<br><br>- Jeanie Halley<br>*Has since lost an additional 15 pounds<br>and has kept it off for over a year!<br><br></b>', '', 'Halley WL');
ajscroller1.add('"My experience with your weight loss program was extremely positive.  <br><br>My first session was April 11, 2002.  I immediately noted behavioral changes that contributed to a consistant weight loss.  I no longer craved sweets late at night nor snacked between meals.  The modification to my behavior included me exercising daily for the first time in my life.  <br><br>I sleep better and feel better than I have felt in years.  Within three months I had achieved my goal."<br><br>- Kathleen Kushnir<br><br>', '', 'Kushnir WL');
ajscroller1.add('<em>"It\'s been since 8-17-02 and I\'m still doing great!  Thank you!!!"<br><br>- Frank Roach<br>Ex-smoker<br><br></em>', '', 'Roach smoking');
ajscroller1.add('<b>"You will never know how much I appreciate you helping me get my life back"<br><br>- J.M.<br>Recovered agoraphobic, post-traumatic<br>stress disorder and abuse survivor<br><br></b>', '', 'JM stress and abuse');
ajscroller1.add('"The stress is greatly reduced since I have learned to hypnotize myself.  <br><br>The tape is so helpful.  I am telling others about it for smoking and weight loss.  <br><br>I feel more in control of my life and have the power to unwind.  The mind control over myself - to relax… breathe… de-stress is wonderful!  I will continue to do this forever.  Thanks!"<br>	<br>- Sandi<br><br><br>', '', 'Sandi Stress');
ajscroller1.add('<em>"A few years ago I found myself feeling discouraged about my weight - I had gained 12 pounds over the course of 5 years and could not seem to successfully diet.  I supposed it was pre-menopause because in my thirties dieting worked for me.  I thought about diet pills, but shied away from that and decided to try hypnosis.  <br><br>Not only did I lose those 12 pounds, after only 2 sessions 4 months ago - I also found myself feeling more relaxed, happier and spiritually renewed.  <br><br>Hypnosis taught me to be more aware of when I am full and I choose more healthy foods naturally today.  <br><br>Daniel Lester is a very caring practitioner and a man who tries hard to make a positive difference."<br><br>- Peggi Newman<br><br><br></em>', '', 'Peggy WL');
ajscroller1.add('<b>When I decided to make an appointment at American Hypnosis Clinic, I was rapidly gaining weight, which was causing many of my health problems.<br><br>I\'ve been seeing Dr. Dan for several months and <br>have lost weight, which has improved my health.<br><br>My self-esteem has risen.<br><br> And my General Practioner is delighted.<br><br>The office Staff has been very supportive and Dr. Dan has put a lot of time and effort into making me feel better about my health and myself.<br><br>Thank you Dr. Dan!<br><br>Dwight<br></b>', '', 'dwight wl');
ajscroller1.add('"Thank you for helping me lose weight through hypnotism.  <br><br> I had attained the weight of 280 lbs and could not stand it any longer. <br><br> After trying many times to get on a sensible pattern of eating, I was told of you by a friend who had come to you to quit smoking.  <br><br>She was successful and I figured if you could help her quit you were a miracle man because she had a 3-4 pack a day habit.  <br><br> I was extremely skeptical that anyone could hypnotize me - much less help me lose weight.<br><br>I was wrong.  <br><br>Through the self-hypnosis that you taught me and the 2 sessions I had with you, <br>I have lost over 80 lbs in 1 year.<br><br>I feel as good as I have ever felt in my life.<br><br>To me, you are a miracle worker.  <br><br>I thank you every day when I get up in the morning and when I go to sleep at night."<br><br>- Alan I. Greene <a href="http://www.americanhypnosisclinic.com/testimonials.htm"> (read his whole testimonial here)</a><br><br><br>', '', 'Greene WL');

/* -- Replicate Items -- */
ajscroller1.display();
onload = function(){
	ajscroller1.load();
	ajscroller1.start();
	};
onresize = function(){
	ajscroller1.load();
	};
